import { PlayerModel } from "../models/player-model";
import { StatisticsModel } from "../models/statistics-model";

const database: PlayerModel[] = [
  {
    id: 1,
    name: "Lionel Messi",
    club: "Inter Miami",
    nationality: "Argentina",
    position: "Forward",
    statistics: {
      Overall: 90,
      Pace: 85,
      Shooting: 94,
      Passing: 91,
      Dribbling: 95,
      Defending: 38,
      Physical: 65,
    },
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    club: "Al-Nassr",
    nationality: "Portugal",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 87,
      Shooting: 93,
      Passing: 82,
      Dribbling: 88,
      Defending: 35,
      Physical: 78,
    },
  },
  {
    id: 3,
    name: "Kylian Mbappé",
    club: "Paris Saint-Germain",
    nationality: "France",
    position: "Forward",
    statistics: {
      Overall: 91,
      Pace: 97,
      Shooting: 89,
      Passing: 80,
      Dribbling: 92,
      Defending: 36,
      Physical: 76,
    },
  },
  {
    id: 4,
    name: "Robert Lewandowski",
    club: "FC Barcelona",
    nationality: "Poland",
    position: "Forward",
    statistics: {
      Overall: 91,
      Pace: 77,
      Shooting: 92,
      Passing: 79,
      Dribbling: 86,
      Defending: 44,
      Physical: 82,
    },
  },
  {
    id: 5,
    name: "Kevin De Bruyne",
    club: "Manchester City",
    nationality: "Belgium",
    position: "Midfielder",
    statistics: {
      Overall: 91,
      Pace: 76,
      Shooting: 86,
      Passing: 93,
      Dribbling: 87,
      Defending: 64,
      Physical: 77,
    },
  },
  {
    id: 6,
    name: "Neymar Jr.",
    club: "Al-Hilal",
    nationality: "Brazil",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 87,
      Shooting: 83,
      Passing: 85,
      Dribbling: 92,
      Defending: 37,
      Physical: 61,
    },
  },
  {
    id: 7,
    name: "Mohamed Salah",
    club: "Liverpool",
    nationality: "Egypt",
    position: "Forward",
    statistics: {
      Overall: 90,
      Pace: 90,
      Shooting: 86,
      Passing: 81,
      Dribbling: 90,
      Defending: 45,
      Physical: 75,
    },
  },
  {
    id: 8,
    name: "Karim Benzema",
    club: "Al-Ittihad",
    nationality: "France",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 78,
      Shooting: 89,
      Passing: 83,
      Dribbling: 87,
      Defending: 39,
      Physical: 78,
    },
  },
  {
    id: 9,
    name: "Harry Kane",
    club: "Bayern Munich",
    nationality: "England",
    position: "Forward",
    statistics: {
      Overall: 90,
      Pace: 70,
      Shooting: 91,
      Passing: 83,
      Dribbling: 84,
      Defending: 47,
      Physical: 83,
    },
  },
  {
    id: 10,
    name: "Erling Haaland",
    club: "Manchester City",
    nationality: "Norway",
    position: "Forward",
    statistics: {
      Overall: 91,
      Pace: 94,
      Shooting: 93,
      Passing: 65,
      Dribbling: 80,
      Defending: 45,
      Physical: 88,
    },
  },
  {
    id: 11,
    name: "Sadio Mané",
    club: "Al-Nassr",
    nationality: "Senegal",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 91,
      Shooting: 84,
      Passing: 78,
      Dribbling: 88,
      Defending: 45,
      Physical: 76,
    },
  },
  {
    id: 12,
    name: "Virgil van Dijk",
    club: "Liverpool",
    nationality: "Netherlands",
    position: "Defender",
    statistics: {
      Overall: 89,
      Pace: 77,
      Shooting: 60,
      Passing: 71,
      Dribbling: 72,
      Defending: 91,
      Physical: 86,
    },
  },
  {
    id: 13,
    name: "Luka Modrić",
    club: "Real Madrid",
    nationality: "Croatia",
    position: "Midfielder",
    statistics: {
      Overall: 88,
      Pace: 70,
      Shooting: 74,
      Passing: 89,
      Dribbling: 91,
      Defending: 72,
      Physical: 66,
    },
  },
  {
    id: 14,
    name: "Toni Kroos",
    club: "Real Madrid",
    nationality: "Germany",
    position: "Midfielder",
    statistics: {
      Overall: 88,
      Pace: 53,
      Shooting: 81,
      Passing: 90,
      Dribbling: 81,
      Defending: 70,
      Physical: 68,
    },
  },
  {
    id: 15,
    name: "Joshua Kimmich",
    club: "Bayern Munich",
    nationality: "Germany",
    position: "Midfielder",
    statistics: {
      Overall: 89,
      Pace: 73,
      Shooting: 72,
      Passing: 86,
      Dribbling: 83,
      Defending: 82,
      Physical: 78,
    },
  },
  {
    id: 16,
    name: "Casemiro",
    club: "Manchester United",
    nationality: "Brazil",
    position: "Midfielder",
    statistics: {
      Overall: 89,
      Pace: 63,
      Shooting: 73,
      Passing: 75,
      Dribbling: 78,
      Defending: 88,
      Physical: 90,
    },
  },
  {
    id: 17,
    name: "Jan Oblak",
    club: "Atletico Madrid",
    nationality: "Slovenia",
    position: "Goalkeeper",
    statistics: {
      Overall: 89,
      Pace: 56,
      Shooting: 40,
      Passing: 52,
      Dribbling: 48,
      Defending: 47,
      Physical: 85,
    },
  },
  {
    id: 18,
    name: "Thibaut Courtois",
    club: "Real Madrid",
    nationality: "Belgium",
    position: "Goalkeeper",
    statistics: {
      Overall: 90,
      Pace: 56,
      Shooting: 40,
      Passing: 49,
      Dribbling: 43,
      Defending: 45,
      Physical: 86,
    },
  },
  {
    id: 19,
    name: "Alisson Becker",
    club: "Liverpool",
    nationality: "Brazil",
    position: "Goalkeeper",
    statistics: {
      Overall: 89,
      Pace: 58,
      Shooting: 40,
      Passing: 53,
      Dribbling: 51,
      Defending: 48,
      Physical: 84,
    },
  },
  {
    id: 20,
    name: "Ederson Moraes",
    club: "Manchester City",
    nationality: "Brazil",
    position: "Goalkeeper",
    statistics: {
      Overall: 88,
      Pace: 62,
      Shooting: 44,
      Passing: 93,
      Dribbling: 70,
      Defending: 46,
      Physical: 79,
    },
  },
  {
    id: 21,
    name: "N'Golo Kanté",
    club: "Al-Ittihad",
    nationality: "France",
    position: "Midfielder",
    statistics: {
      Overall: 88,
      Pace: 73,
      Shooting: 66,
      Passing: 74,
      Dribbling: 81,
      Defending: 87,
      Physical: 83,
    },
  },
  {
    id: 22,
    name: "Bernardo Silva",
    club: "Manchester City",
    nationality: "Portugal",
    position: "Midfielder",
    statistics: {
      Overall: 88,
      Pace: 79,
      Shooting: 77,
      Passing: 84,
      Dribbling: 92,
      Defending: 63,
      Physical: 67,
    },
  },
  {
    id: 23,
    name: "Son Heung-min",
    club: "Tottenham Hotspur",
    nationality: "South Korea",
    position: "Forward",
    statistics: {
      Overall: 88,
      Pace: 89,
      Shooting: 87,
      Passing: 82,
      Dribbling: 86,
      Defending: 43,
      Physical: 69,
    },
  },
  {
    id: 24,
    name: "Bruno Fernandes",
    club: "Manchester United",
    nationality: "Portugal",
    position: "Midfielder",
    statistics: {
      Overall: 88,
      Pace: 74,
      Shooting: 84,
      Passing: 88,
      Dribbling: 83,
      Defending: 70,
      Physical: 76,
    },
  },
  {
    id: 25,
    name: "Trent Alexander-Arnold",
    club: "Liverpool",
    nationality: "England",
    position: "Defender",
    statistics: {
      Overall: 87,
      Pace: 80,
      Shooting: 66,
      Passing: 92,
      Dribbling: 81,
      Defending: 80,
      Physical: 69,
    },
  },
  {
    id: 26,
    name: "Joshua Kimmich",
    club: "Bayern Munich",
    nationality: "Germany",
    position: "Defender",
    statistics: {
      Overall: 89,
      Pace: 73,
      Shooting: 72,
      Passing: 86,
      Dribbling: 83,
      Defending: 82,
      Physical: 78,
    },
  },
  {
    id: 27,
    name: "Raheem Sterling",
    club: "Chelsea",
    nationality: "England",
    position: "Forward",
    statistics: {
      Overall: 87,
      Pace: 91,
      Shooting: 81,
      Passing: 78,
      Dribbling: 88,
      Defending: 44,
      Physical: 66,
    },
  },
  {
    id: 28,
    name: "Marquinhos",
    club: "Paris Saint-Germain",
    nationality: "Brazil",
    position: "Defender",
    statistics: {
      Overall: 88,
      Pace: 76,
      Shooting: 55,
      Passing: 70,
      Dribbling: 72,
      Defending: 90,
      Physical: 82,
    },
  },
  {
    id: 29,
    name: "Phil Foden",
    club: "Manchester City",
    nationality: "England",
    position: "Midfielder",
    statistics: {
      Overall: 88,
      Pace: 83,
      Shooting: 78,
      Passing: 84,
      Dribbling: 91,
      Defending: 52,
      Physical: 65,
    },
  },
  {
    id: 30,
    name: "Vinícius Júnior",
    club: "Real Madrid",
    nationality: "Brazil",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 95,
      Shooting: 84,
      Passing: 79,
      Dribbling: 92,
      Defending: 33,
      Physical: 74,
    },
  },
];

export const findAllPlayers = async (): Promise<PlayerModel[]> => {
  return database;
};

export const findPlayerById = async (
  id: number
): Promise<PlayerModel | undefined> => {
  return database.find((player) => player.id === id);
};

export const insertPlayer = async (player: PlayerModel) => {
  database.push(player);
};

export const deleteOnePlayer = async (id: number) => {
  const index = database.findIndex((p) => p.id === id);

  if (index !== -1) {
    database.splice(index, 1);
    return true;
  }

  return false;
};

export const findAndModifyPlayer = async (
  id: number,
  statistics: StatisticsModel
): Promise<PlayerModel> => {
  const playerIndex = database.findIndex((player) => player.id === id);

  if (playerIndex !== -1) {
    database[playerIndex].statistics = statistics;
  }
  return database[playerIndex];
};
